//
// Created by David Exinor on 2024-04-24.
//

#ifndef MUSIC_LIBRARY_TRANSFER_APP_CONVERTER_H
#define MUSIC_LIBRARY_TRANSFER_APP_CONVERTER_H


class Converter {

};


#endif //MUSIC_LIBRARY_TRANSFER_APP_CONVERTER_H
